language: node_js
node_js:
  - "node"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "9"
  - "8"
  - "6"
  - "4"
install: npm install
script: npm test
after_script: npm install coveralls && npm run coverage && cat ./coverage/lcov.info | coveralls
